function set_configset(cell,Mobj,configsetobj_in)
%SET_CONFIGSET set the configset in Mobj (simbiology model object)
%according to configsetobj_in
%the followed species are set according to "cell"

configsetobj_out = getconfigset(Mobj);
set(configsetobj_out,'SolverType',configsetobj_in.SolverType, ...
    'Stoptime',configsetobj_in.Stoptime,'TimeUnit',configsetobj_in.TimeUnit,...
    'MaximumWallClock',configsetobj_in.MaximumWallClock)
set(get(configsetobj_out,'CompileOptions'),...
    'Dimensionalanalysis',configsetobj_in.CompileOptions.Dimensionalanalysis,...
    'UnitConversion',configsetobj_in.CompileOptions.UnitConversion)
set(get(configsetobj_out,'SolverOptions'), ...
    'AbsoluteTolerance',configsetobj_in.SolverOptions.AbsoluteTolerance,...
    'RelativeTolerance',configsetobj_in.SolverOptions.RelativeTolerance, ...
    'OutputTimes',configsetobj_in.SolverOptions.OutputTimes)
% set the logged properties
%             configsetobj_out.RuntimeOptions.StatesToLog = cell.data.StatesToLog;
set(get(configsetobj_out,'RuntimeOptions'),'StatesToLog',strcat('[',cell.data.StatesToLog,']'))

end

